const express = require('express');
const controllers = require('../../controllers');
const router = express.Router();
const {InfoController} = require('../../controllers');
const airplaneRoutes=require('./airplane-routes');
const cityRoutes = require('./city-routes');
router.get('/info',InfoController.info);
router.use('/airplane',airplaneRoutes);
router.use('/city',cityRoutes);
module.exports=router;